### ISSUE TITLE
add command line for wpt-graph

### ISSUE THREAD

**Issue by Finkregh** [sitespeedio/doc.sitespeed.io#19]
The command line for the WPT-graph in https://github.com/sitespeedio/doc.sitespeed.io/blob/master/documentation/graphs/index.md is missing

**Comment by soulgalore** [comment]
great will add it tonight.

**Comment by soulgalore** [comment]
I've pushed it live now, thanks for reporting:
http://www.sitespeed.io/documentation/graphs/

Also added the cron setup for the dashboard:
http://www.sitespeed.io/documentation/performance-dashboard/#crontab-setup-for-dashboardsitespeedio

Will all config files tonight.
